<blockquote><pre>
	local.inc has not been autogen'd.

	This file must be replaced by the one created by the autogenerator.
	Please click the link below to generate the local.inc

	You may want to add more tables to the database using phpmyadmin
	or whatever, beforehand so that the generator will also generate 
	php from them too.  autogen may be run at any time to generate
	php for new tables or update existing ones.

	<a href="phplib/autogen.php">phplib/autogen.php</a>
</blockquote>
<?php
	exit;
?>
